
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://120.24.186.116:3306/${DATABASE_NAME:sirius}?useUnicode=true&characterEncoding=utf8
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:geralt}
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: >
    com.qtu404.sirius.model